### DISCUSSION TITLE
Does Android app supports https?

### DISCUSSION THREAD

**Discussion by Godd67** [advplyr/audiobookshelf-app#89] [Q&A]
I run audiobookshelf on RPI4 in docker behind traefik&cloudflare.
 I can connect from outside with my subdomain name https://books.mydomain.com using browsers but android app rejects connection with "Server did not respond" error.  App works fine if I connect directly to http://192.168.x.x:port

Is it a way to workaround this issue or https is just not supported yet?

Thanks,

**Comment by jcrmit** [comment]
Hey @Godd67 - I use the same set-up traefik (with Google Auth) and cloudflare; but ended up removing traefik (with Google Auth) for this docker and leave this to the apps login for security - less secure but works. Not sure how complex it would be to support this?

**Comment by advplyr** [comment]
It is supported and other users have that setup working.

https://github.com/advplyr/audiobookshelf-app/issues/28

https://github.com/advplyr/audiobookshelf-app/issues/36#issuecomment-977804251

**Comment by Godd67** [comment]
Thanks! 
I looked at suggested  traefik example here - [#36](https://github.com/advplyr/audiobookshelf-app/issues/36#issuecomment-977804251)
but unfortunately it did not help in my case. I have very similar setup, I removed rate-limit middleware as suggested and tweak headers, but nothing  changed for me so far.

**Reply by advplyr** [reply]
Are you able to play audiobooks from the mobile browser?

**Comment by Godd67** [comment]
Yes, mobile browser worked.

On Tue, Feb 1, 2022 at 10:24 AM advplyr ***@***.***> wrote:

> Are you able to play audiobooks from the mobile browser?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/advplyr/audiobookshelf-app/discussions/89#discussioncomment-2089789>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKF3ONVWLG7UYDCEJABXH3UY73MDANCNFSM5MUE276Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>


-- 
Regards,
Oleg

**Reply by advplyr** [reply]
This is the same issue as in #28, it is an issue with your certificate. Your ssl ceritifcate needs to be installed on your android device. Have you looked into that?
https://proxyman.io/posts/2020-09-29-Install-And-Trust-Self-Signed-Certificate-On-Android-11

**Comment by Godd67** [comment]
I already have several apps behind same traefik proxy with Android apps working correctly . Traefik handles server certificates from LE by itself, they are not self-signed.  
For instance I have booksonic-air sitting near audiobookshelf and booksonic android app connects to my server without issues.

**Comment by typhooncarr** [comment]
You might want to try the following setup.

```
http:
  middlewares:
    rate-limit:
      rateLimit:
        average: 100
        burst: 50

http:
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

http:
  middlewares:
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
        accessControlMaxAge: 100
        accessControlAllowHeaders: X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization, Origin, Accept
        accessControlAllowOriginList: '*'
        accessControlAllowCredentials: true
        accessControlExposeHeaders: '*, Authorization'
        addVaryHeader: true
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslProxyHeaders: 
          X-Forwarded-Proto: "https"
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        customFrameOptionsValue: 'allow-from https:example.com'
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), xr-spatial-tracking=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nofollow,noimageindex,noindex,nosnippet,notranslate"
          server: ""
        customRequestHeaders:
          X-Forwarded-Proto: "https"

http:
  middlewares:
    compress:
      compress: {}

http:
  middlewares:
    nofloc:
      headers:
        customResponseHeaders:
          Permissions-Policy: "interest-cohort=()"
```
[#554](https://github.com/advplyr/audiobookshelf/discussions/554)
