### ISSUE TITLE
Android App crashes when trying to download an audiobook

### ISSUE THREAD

**Issue by TheLux83** [advplyr/audiobookshelf-app#144]
### Steps to reproduce

1. Define a folder
2. Try to download an audiobook

### Expected behaviour
- Downloading of the audio book

### Actual behaviour
- Either the app crashes (Tried with two folders which were named audiobookshelf and test) or it just hangs at "Downloading!" (When using an already existing audiobooks folder) and after a given time android throws an error, that it couldn't download cover.jpeg and audiobookname.m4a

### Environment data

Audiobookshelf Version: 2.0.2

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 0.9.41-beta

Device model: Google Pixel 3

Stock or customized system: Stock

#### iOS Issue
iOS Version:

iPhone model:

Hey there,

to add a few things to the details above:
- I'm using the docker image with the following docker-compose code
```
  audiobookshelf:
    container_name: audiobookshelf
    image: advplyr/audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /media/data/shary/Audiobooks:/audiobooks
      - audiobookshelf_metadata:/metadata
      - audiobookshelf_config:/config
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
```
The docker volumes were defined, too and the permissions should be correct.
I didn't set "Store covers with item" and "Store metadata with item" in the settings, but I also tested it with both setting options set.

Another maybe interesting fact is, that the android app isn't able to show author images even though the web app is able to.
The docker logs don't show anything interesting when the app crashes or fails to download
```
audiobookshelf        | [2022-04-24T20:01:16.330Z]  INFO: [Server] Socket eaAZY5nXzA1kfqh0AAAF disconnected from client "sascham" after 210915ms
audiobookshelf        | [2022-04-24T20:01:21.378Z]  INFO: [Server] Socket Connected CxADweT8doZw8M1KAAAH
audiobookshelf        | [2022-04-24T20:01:34.496Z]  INFO: [Server] Socket CxADweT8doZw8M1KAAAH disconnected from client "sascham" after 13118ms
audiobookshelf        | [2022-04-24T20:01:43.482Z]  INFO: [Server] Socket Connected XKDwNDbZSkwEI1bfAAAJ
audiobookshelf        | [2022-04-24T20:02:11.278Z]  INFO: [Server] Socket XKDwNDbZSkwEI1bfAAAJ disconnected from client "sascham" after 27796ms
```

I'm able to stream an audiobook in the web app and in the android app without any problems.

I think it may be a permission issue, but I cannot point with the finger at it. I even set 777 to the audiobook folder to test it, but that didn't help.

Can someone help me here?
