### ISSUE TITLE
[Bug] Collapse Series - This Page Could Not Be Found

### ISSUE THREAD

**Issue by realmain** [advplyr/audiobookshelf-app#850]
### Steps to reproduce

1. Go to Library Tab
2. Click on the 3 dots on top right
3. Toggle **Collapse Series**
4. Click on a book that is part of a series

### Expected behaviour
It should take you to the book series.

### Actual behaviour
It takes you to **This page could not be found**

![Screenshot_20230830-083037](https://github.com/advplyr/audiobookshelf-app/assets/22500082/9d7d323c-8d7b-446a-97be-160cda730f02)

Another thing I noticed is that when you **Collapse Series** in the app, it shows the name of the first book and total read time instead of the series name. I wonder if this is what is causing the issue.

When you **Collapse Series** on the Web GUI, it shows the series name.

Seems to be similar issue to #793, but they said theirs is fixed.

### Environment data

Audiobookshelf Version: 0.9.65-beta

- [X] Android App?
- [ ] iOS App?

#### Android Issue
Android version: 13

Device model: Pixel 7 Pro

Stock or customized system: GrapheneOS

#### Hosting on

Docker v.2.3.3

**Comment by advplyr** [comment]
Have you tested if this is because the book of the series is downloaded?

**Comment by realmain** [comment]
I am only streaming directly from my server, not downloading any of it to listen to offline.

**Comment by advplyr** [comment]
Are you using `:latest` or `:edge` or `:2.3.3` when running the docker container?

**Comment by realmain** [comment]
```
version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /var/lib/docker/volumes/audiobookshelf/audiobooks:/audiobooks
      - /var/lib/docker/volumes/audiobookshelf/podcasts:/podcasts
      - /var/lib/docker/volumes/audiobookshelf/config:/config
      - /var/lib/docker/volumes/audiobookshelf/metadata:/metadata
    restart: unless-stopped
```
