### ISSUE TITLE
Covers break when moving `metadata` path

### ISSUE THREAD

**Issue by watsonbox** [advplyr/audiobookshelf-app#900]
### Steps to reproduce

1. Install Audiobookshelf on Linux (metadata in `/usr/share/audiobookshelf/metadata`)
2. Move the installation to Docker (metadata in `/metadata`)
3. Restore from a backup

### Expected behaviour

In this case I'd expect all metadata, including covers, to still work and be accessible from the new `metadata` path even though it changed.

### Actual behaviour

Covers are not visible (404 not found errors). I can see from the cover tab that the old metadata path is still saved as part of the cover file path, presumably in the database itself:

<img width="1017" alt="image" src="https://github.com/advplyr/audiobookshelf-app/assets/17737/d9705642-5f47-4efd-bccc-0943b951338d">

**Would it be possible to store the paths _relative_ to the configured metadata path?**

Incidentally, I was able to work around this with the following `docker-compose` setup:

```yaml
environment:
  - METADATA_PATH=/usr/share/audiobookshelf/metadata
volumes:
  - ./metadata:/usr/share/audiobookshelf/metadata
```

### Environment data

Audiobookshelf Version: 2.4.4

- [ ] Android App?
- [ ] iOS App?
