### ISSUE TITLE
OIDC login (provided by Authelia) not working in the iOS app

### ISSUE THREAD

**Issue by rabidpug** [advplyr/audiobookshelf-app#993]
OIDC login is working as expected via browser, but when trying to login on the iOS app I receive the error "SSO error: Token data is missing in the response".
in Authelia and Audiobookshelf's logs, I see the error "Access Request failed with error: The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. The 'redirect_uri' from this request does not match the one from the authorize request."

Authelia configuration:

```yaml
- id: audiobookshelf
        description: audiobookshelf
        secret: '[SECRET]'
        sector_identifier: ''
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: '30d'
        audience: []
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - https://[DOMAIN]/auth/openid/callback
          - audiobookshelf://oauth
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - query
          - form_post
        userinfo_signed_response_alg: none
```

### Steps to reproduce

1. Try to log in with OpenID on the mobile app

### Expected behaviour
- Login should be successful

### Actual behaviour
- Login is not successful

### Environment data

Audiobookshelf Version: 2.6.0

- [Y ] iOS App?

#### iOS Issue
iOS Version: iOS 17.3

iPhone model: iphone 12
